modcluster/mod_cluster

- core/src/test/java/org/jboss/modcluster/advertise/AdvertiseListenerImplTestCase.java
- core/src/test/java/org/jboss/modcluster/advertise/MulticastSocketFactoryImplTestCase.java
In case we decide to proceed with the Beta release...
> MODCLUSTER-432 Ignore failing tests on Mac OS X (Maverics)

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
- test/java/src/main/java/org/jboss/mod_cluster/Client.java
Actually after some testing it is probably better to have a switch and that the feature is off by default.
> Improvement related towebsocket proxying

- core/src/main/java/org/jboss/modcluster/config/impl/ModClusterConfig.java
- docs/userguide/src/main/docbook/modules/native/install.xml
- docs/userguide/src/main/docbook/modules/quick-start.xml
- site-mod_cluster/constants.sh
Note that the most problematic one is BZ 822250.
> Various small things.

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
See [MODCLUSTER-458](https://issues.jboss.org/browse/MODCLUSTER-458) for details.
> MODCLUSTER-458 Enhanced logging and response header error messages.

- core/src/main/java/org/jboss/modcluster/config/impl/ModClusterConfig.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-456
> MODCLUSTER-456 Fix compilation on JDK 6

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.jboss.org/browse/MODCLUSTER-466
> [MODCLUSTER-466] set connection pool max to max threads + 1

- native/include/mod_proxy_cluster.h
- native/mod_manager/mod_manager.c
This is now public but missing in the right branch...
> MODCLUSTER-453

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.jboss.org/browse/MODCLUSTER-397
> [MODCLUSTER-397] StickySessions don't work for ProxyPass from unenabled context

- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPRequestFactory.java
Jira
https://issues.jboss.org/browse/JBEAP-1767
> MODCLUSTER-483 Remove zone id completely from CONFIG command

- container-spi/pom.xml
- container/catalina-standalone/pom.xml
- container/catalina/pom.xml
- container/jbossweb/pom.xml
- container/pom.xml
- container/tomcat6/pom.xml
- container/tomcat7/pom.xml
- container/tomcat8/pom.xml
- core/pom.xml
- demo/client/pom.xml
- demo/pom.xml
- demo/server/pom.xml
- docs/pom.xml
- docs/userguide/pom.xml
- native/include/mod_proxy_cluster.h
- pom.xml
- sar/pom.xml
- test/java/pom.xml
Go, go, go!
Move to nonblocking I/O (multicast logic)
Drop legacy versions (e.g. sar)
Tomcat 9 support (already wip)
Move to CMAKE (wip)
Separate C native code
Project rename
Protocol versioning
etc
> Move master to 2.x!

- README.md
- container/catalina/pom.xml
- container/catalina/src/main/java/org/jboss/modcluster/container/catalina/CatalinaEventHandlerAdapter.java
- container/pom.xml
- container/tomcat9/pom.xml
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnectorFactory.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatContext.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatContextFactory.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEngine.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEngineFactory.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatLifecycleListenerFactory.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatServer.java
- container/tomcat9/src/main/java/org/jboss/modcluster/container/tomcat/TomcatServerFactory.java
- container/tomcat9/src/main/resources/META-INF/services/org.jboss.modcluster.container.catalina.ConnectorFactory
- container/tomcat9/src/main/resources/META-INF/services/org.jboss.modcluster.container.catalina.ContextFactory
- container/tomcat9/src/main/resources/META-INF/services/org.jboss.modcluster.container.catalina.EngineFactory
- container/tomcat9/src/main/resources/META-INF/services/org.jboss.modcluster.container.catalina.LifecycleListenerFactory
- container/tomcat9/src/main/resources/META-INF/services/org.jboss.modcluster.container.catalina.ServerFactory
- container/tomcat9/src/test/java/org/jboss/modcluster/container/tomcat/ConnectorTestCase.java
- container/tomcat9/src/test/java/org/jboss/modcluster/container/tomcat/ContextTestCase.java
- container/tomcat9/src/test/java/org/jboss/modcluster/container/tomcat/EngineTestCase.java
- container/tomcat9/src/test/java/org/jboss/modcluster/container/tomcat/HostTestCase.java
- container/tomcat9/src/test/java/org/jboss/modcluster/container/tomcat/ServerTestCase.java
- container/tomcat9/src/test/java/org/jboss/modcluster/container/tomcat/ServiceLoaderCatalinaFactoryTestCase.java
- container/tomcat9/src/test/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapterTestCase.java
- pom.xml
- src/assembly/bin.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-479
> MODCLUSTER-479 Add support for Tomcat 9

- native/mod_manager/mod_manager.c
* reorganizing process buffer functions
* decodeenc function optimization
> maintenance on mod_manager functions

- native/mod_manager/domain.c
- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
* some basic optimizations on command processing
* modernizing the old codebase and housekeeping
> Command processing optimizations and code modernizations.

- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
* some basic optimizations on command processing
* modernizing the old codebase and housekeeping
> [1.3] Commands processing optimizations.

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-517
> MODCLUSTER-517 Upgrade jboss-parent to 21

- pom.xml
While at it, bumping logging dependencies to sync with WildFly.
https://issues.jboss.org/browse/MODCLUSTER-518
https://issues.jboss.org/browse/MODCLUSTER-520
> MODCLUSTER-518 Support JDK 9

- .travis.yml
Jira
https://issues.jboss.org/browse/MODCLUSTER-485
Upstream (already done)
https://github.com/modcluster/mod_cluster/pull/200
> [1.3] MODCLUSTER-485 Move CI to Travis

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-539
> MODCLUSTER-539 Support JDK9 build 9-ea+139

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.jboss.org/browse/MODCLUSTER-550
Upstream PR:
https://github.com/modcluster/mod_proxy_cluster/pull/8
> [1.2.x] MODCLUSTER-550 Failover targets should be chosen deterministically

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.jboss.org/browse/MODCLUSTER-550
Upstream PR:
https://github.com/modcluster/mod_proxy_cluster/pull/8
> [1.3.x] MODCLUSTER-550 Failover targets should be chosen deterministically

- native/mod_proxy_cluster/mod_proxy_cluster.c
Do not merge yet, please. This is work in progress.
See discussion on [MODCLUSTER-526](https://issues.jboss.org/browse/MODCLUSTER-526).
> WIP [MODCLUSTER-526] We don't use helper->shared if it's already NULL.

- container/catalina/src/test/java/org/jboss/modcluster/container/catalina/AutoProxyConnectorProviderTestCase.java
- container/catalina/src/test/java/org/jboss/modcluster/container/catalina/ContainerEventHandlerAdapterTestCase.java
- container/catalina/src/test/java/org/jboss/modcluster/container/catalina/ContextTestCase.java
- container/catalina/src/test/java/org/jboss/modcluster/container/catalina/JMXServerProviderTestCase.java
- container/catalina/src/test/java/org/jboss/modcluster/container/catalina/ServerTestCase.java
- container/catalina/src/test/java/org/jboss/modcluster/container/catalina/SimpleProxyConnectorProviderTestCase.java
- container/jbossweb/src/test/java/org/jboss/modcluster/container/jbossweb/ContextTestCase.java
- container/jbossweb/src/test/java/org/jboss/modcluster/container/jbossweb/JBossWebEventHandlerAdapterTestCase.java
- container/tomcat6/src/test/java/org/jboss/modcluster/container/tomcat/ContextTestCase.java
- container/tomcat7/src/test/java/org/jboss/modcluster/container/tomcat/ContextTestCase.java
- container/tomcat8/src/test/java/org/jboss/modcluster/container/tomcat/ContextTestCase.java
- core/src/test/java/org/jboss/modcluster/load/metric/MBeanAttributeLoadMetricTestCase.java
- core/src/test/java/org/jboss/modcluster/load/metric/MBeanAttributeRatioLoadMetricTestCase.java
- pom.xml
https://github.com/modcluster/mod_cluster/pull/232
> MODCLUSTER-560 Upgrade mockito to 2.5.2

- native/mod_proxy_cluster/buildconf
Hello, please see this trivial change. Thanks!
> Add missing shebang

- core/src/main/java/org/jboss/modcluster/ModClusterService.java
- core/src/main/java/org/jboss/modcluster/mcmp/ContextFilter.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/ResetRequestSourceImpl.java
- core/src/test/java/org/jboss/modcluster/mcmp/ResetRequestSourceTestCase.java
https://issues.jboss.org/browse/MODCLUSTER-566
> MODCLUSTER-566 Exclusion list cannot be pre-populated in init()

- native/mod_proxy_cluster/mod_proxy_cluster.c
Due to a regression in MODCLUSTER-376
> Fix for MODCLUSTER-568.

- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPRequestFactory.java
https://issues.jboss.org/browse/MODCLUSTER-572
> MODCLUSTER-572 Normalize hostnames in MCMP messages

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-559
> MODCLUSTER-559 Support JDK9 build 9-ea+160

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-597
> MODCLUSTER-597 Upgrade jboss-parent to 24 (to support jdk-9+175)

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-597
https://github.com/modcluster/mod_cluster/pull/266
> 	MODCLUSTER-597 Upgrade jboss-parent to 24 (to support jdk-9+175)

- .travis.yml
- pom.xml
- sar/pom.xml
- src/assembly/sar.xml
Jiras
https://issues.jboss.org/browse/MODCLUSTER-598
https://issues.jboss.org/browse/MODCLUSTER-599
Upstream
https://github.com/modcluster/mod_cluster/pull/269
> [1.3] MODCLUSTER-598 Include building the distribution profile in CI

- .travis.yml
- pom.xml
Jiras
https://issues.jboss.org/browse/MODCLUSTER-598
https://issues.jboss.org/browse/MODCLUSTER-599
> MODCLUSTER-598 Include building the distribution profile in CI

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-519
> MODCLUSTER-519 Upgrade Tomcat versions to 8.5.20, 9.0.0.M26

- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/ModClusterListener.java
- core/src/main/java/org/jboss/modcluster/load/impl/DynamicLoadBalanceFactorProvider.java
- core/src/main/java/org/jboss/modcluster/load/impl/DynamicLoadBalanceFactorProviderMBean.java
- core/src/test/java/org/jboss/modcluster/load/impl/DynamicLoadBalanceFactorProviderTest.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-607
> MODCLUSTER-607 Support floating-point numerals for decay factor

- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/ModClusterListener.java
- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/mbeans-descriptors.xml
- core/src/main/java/org/jboss/modcluster/ModClusterLogger.java
- core/src/main/java/org/jboss/modcluster/load/impl/DynamicLoadBalanceFactorProvider.java
- core/src/test/java/org/jboss/modcluster/load/impl/DynamicLoadBalanceFactorProviderTest.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-449
> MODCLUSTER-449 Implement ramp-up when starting new nodes

- demo/client/src/main/java/org/jboss/modcluster/demo/client/ModClusterDemo.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-615
> MODCLUSTER-615 Revert "[MODCLUSTER-358] demo does not compile on JDK6"

- container/spi/src/main/java/org/jboss/modcluster/container/Context.java
- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/TomcatServer.java
- core/src/main/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerFactoryImpl.java
- core/src/main/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerImpl.java
- core/src/main/java/org/jboss/modcluster/advertise/impl/MulticastSocketFactoryImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/SimpleJvmRouteFactory.java
- core/src/main/java/org/jboss/modcluster/load/impl/SimpleLoadBalanceFactorProvider.java
- core/src/main/java/org/jboss/modcluster/mcmp/MCMPHandler.java
- core/src/main/java/org/jboss/modcluster/mcmp/MCMPRequestFactory.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPHandler.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/ResetRequestSourceImpl.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/ActiveSessionsLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/BusyConnectorsLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/HeapMemoryLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/ReceiveTrafficLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/RecordServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/RequestCountLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/SendTrafficLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/SystemLoadServlet.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-616
Sort of a personal pet peeve and very annoying warnings in IDE.
> MODCLUSTER-616 Fix Javadoc issues

- native/mod_manager/node.c
back ported from mod_cluster-proxy master.
> MODCLUSTER-622 segfault in process_info

- .travis.yml
- docs/userguide/pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-628
> MODCLUSTER-628 Travis CI: Add oraclejdk9 to the matrix

- .travis.yml
- docs/userguide/pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-628
> [1.4] MODCLUSTER-628 Travis CI: Add oraclejdk9 to the matrix

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-519
> [2.0] MODCLUSTER-519 Upgrade Tomcat versions to 7.0.82, 8.0.47, 8.5.23, 9.0.1

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-629
> MODCLUSTER-629 Upgrade jboss-parent to 25

- core/src/test/java/org/jboss/modcluster/TestUtils.java
- core/src/test/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerImplTestCase.java
https://issues.jboss.org/browse/MODCLUSTER-633
>  MODCLUSTER-633 AdvertiseListenerImplTestCase fails intermittently

- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPHandler.java
https://issues.jboss.org/browse/MODCLUSTER-639
> MODCLUSTER-639 proxy reset requests can allow for other MCMPs to bad proxy

- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPHandler.java
https://issues.jboss.org/browse/MODCLUSTER-639
> [1.4] MODCLUSTER-639 proxy reset requests can allow for other MCMPs to bad proxy

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-642
Let's see which other branches we should port this to.
> MODCLUSTER-642 Support JDK10 build 10+44

- container/spi/src/main/java/org/jboss/modcluster/container/Connector.java
- container/spi/src/main/java/org/jboss/modcluster/container/Context.java
- container/spi/src/main/java/org/jboss/modcluster/container/Engine.java
- container/spi/src/main/java/org/jboss/modcluster/container/Host.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-643
Quick effort to clarify the SPI for implementers.
> MODCLUSTER-643 Misleading JavaDoc for SPI Container Engine

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-659
> MODCLUSTER-659 Upgrade jboss-parent to 28

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-661
Upstream
https://github.com/modcluster/mod_cluster/pull/338
> MODCLUSTER-661 Define license in pom.xml

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-662
> MODCLUSTER-662 Upgrade jboss-parent to 29

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-664
> MODCLUSTER-664 Upgrade org.apache.httpcomponents:httpclient to 4.3.6

- .travis.yml
- core/src/test/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerImplTestCase.java
- pom.xml
Jiras
https://issues.jboss.org/browse/MODCLUSTER-671
https://issues.jboss.org/browse/MODCLUSTER-630
> MODCLUSTER-671 Drop support for JDKs prior to 8

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-677
https://issues.jboss.org/browse/MODCLUSTER-678
> MODCLUSTER-677 Upgrade com.puppycrawl.tools:checkstyle and  MODCLUSTER-678 Upgrade org.wildfly.checkstyle-config

- CODE_OF_CONDUCT.md
https://issues.jboss.org/browse/MODCLUSTER-674
> MODCLUSTER-674 Contributor Code of Conduct

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.jboss.org/browse/JBCS-634
> [JBCS-634] decrease loops per vhosts for balancer changes

- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat/src/test/java/org/jboss/modcluster/container/tomcat/ConnectorTestCase.java
See http://tomcat.apache.org/tomcat-9.0-doc/config/http.html#Standard_Implementation looks for SSLEnabled.
> Fix for MODCLUSTER-680.

- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat/src/test/java/org/jboss/modcluster/container/tomcat/ConnectorTestCase.java
https://issues.jboss.org/browse/MODCLUSTER-680
> [1.4]  Fix for MODCLUSTER-680.

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-685
> MODCLUSTER-685 Upgrade jboss-parent to 34

- pom.xml
Jiras
https://issues.jboss.org/browse/MODCLUSTER-691
https://issues.jboss.org/browse/MODCLUSTER-692
>  MODCLUSTER-691 Upgrade jboss-logging to 3.4.0.Final +  MODCLUSTER-692 Upgrade jboss-logging-processor to 2.2.0.Final

- install-jdk.sh
- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-693
>  MODCLUSTER-693 Upgrade jboss-parent to 35

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-693
> [1.4]  MODCLUSTER-693 Upgrade jboss-parent to 35

- native/mod_proxy_cluster/mod_proxy_cluster.c
Signed-off-by: Michal Karm Babacek <karm@email.cz>
> Fixes deterministic failover capability for 1.3.x [MODCLUSTER-590] [MODCLUSTER-675] [MODCLUSTER-697]

- core/src/main/java/org/jboss/modcluster/ModClusterService.java
- core/src/test/java/org/jboss/modcluster/ModClusterServiceTest.java
1.4.x
https://github.com/modcluster/mod_cluster/pull/406
> [master] MODCLUSTER-700 mod_cluster doesn't consider parallel deployment while removing context

- pom.xml
https://issues.redhat.com/browse/MODCLUSTER-708
> MODCLUSTER-708 Upgrade Maven Checkstyle Plugin to 3.1.0

- container/tomcat/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- container/tomcat85/src/test/java/org/jboss/modcluster/container/tomcat85/TomcatEventHandlerAdapterTestCase.java
- core/src/test/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerImplTestCase.java
- core/src/test/java/org/jboss/modcluster/mcmp/ResetRequestSourceTestCase.java
Jira
https://issues.redhat.com/browse/MODCLUSTER-705
> MODCLUSTER-705 Replace usage of deprecated mockito methods

- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/ActiveSessionsLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/BusyConnectorsLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/ReceiveTrafficLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/RequestCountLoadServlet.java
- demo/server/src/main/java/org/jboss/modcluster/demo/servlet/SendTrafficLoadServlet.java
https://issues.redhat.com/browse/MODCLUSTER-706
> MODCLUSTER-706 Bump httpclient from 4.3.6 to 4.5.10

- core/src/test/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerImplTestCase.java
- pom.xml
https://issues.redhat.com/browse/MODCLUSTER-710
> Bump mockito-core from 3.2.0 to 3.2.4

- native/include/node.h
- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
> 1.3.x fix https://issues.redhat.com/browse/MODCLUSTER-712 

- native/include/mod_clustersize.h
- native/include/node.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
upstream:
[]([](https://github.com/modcluster/mod_proxy_cluster/commitf1281d42b9b07c4b56fc54801c64003d0c89fed7))
> Fix for https://issues.redhat.com/browse/MODCLUSTER-580

- pom.xml
Reverts modcluster/mod_cluster#445
> Revert "Bump version.tomcat7 from 7.0.99 to 7.0.103"

- native/include/balancer.h
- native/include/context.h
- native/include/domain.h
- native/include/host.h
- native/include/jgroupsid.h
- native/include/mod_clustersize.h
- native/include/node.h
- native/include/sessionid.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Backport https://issues.redhat.com/browse/MODCLUSTER-714.
And clean warnings/errors when using --enable-maintainer-mode
> [1.3] Backport https://issues.redhat.com/browse/MODCLUSTER-714 and clean.

- native/include/mod_proxy_cluster.h
- native/mod_proxy_cluster/mod_proxy_cluster.c
Back port of upstream: https://github.com/modcluster/mod_proxy_cluster/pull/26/commits/17308dedd94dd64b6c40a8a3e5fc2490ae75e74a
> Fix for https://issues.redhat.com/browse/MODCLUSTER-718

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
The fix removes the messup with the good mod_proxy default values.
upstream PR: https://github.com/modcluster/mod_proxy_cluster/pull/27
> Fix https://issues.redhat.com/browse/MODCLUSTER-721

- .github/workflows/ci.yml
- pom.xml
> Bump version.tomcat100 from 10.0.0-M5 to 10.0.0

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
1.3.x backport of https://github.com/modcluster/mod_proxy_cluster/pull/29 for fixing https://issues.redhat.com/browse/MODCLUSTER-722
> [1.3] Backporting fix for MODCLUSTER-722

- native/mod_proxy_cluster/mod_proxy_cluster.c
> Adding normalize_hostname from mod_proxy_cluster master

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-722
In fact the patch patch was incomplete....
See https://issues.redhat.com/browse/JBCS-1053 for the core problem...
> The fix for MODCLUSTER-722 was incomplete, mod_cluster was coring on failover.

- pom.xml
Thanks for submitting your Pull Request!
Please delete this text, and add a link to the Jira issue solved by this PR.
If this change is relevant upstream/downstream link the correspoding PR for that branch.
Remember to use the Jira issue ID (the identifier starting with MODCLUSTER) in the PR title, and any commits.
> Bump tomcat to 10.0.4

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Upstream PR https://github.com/modcluster/mod_proxy_cluster/pull/28 merged.
https://issues.redhat.com/browse/MODCLUSTER-724
> [1.3] Fix for MODCLUSTER-724

- native/include/node.h
- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-732
No PR for mod_proxy_cluster for the moment.
> Fix for https://issues.redhat.com/browse/MODCLUSTER-732

- native/mod_proxy_cluster/mod_proxy_cluster.c
Add assert to restart the process and prevent the need of httpd restart
> https://issues.redhat.com/browse/MODCLUSTER-736 "fix" for JBCS-1236

- .github/workflows/ci.yml
- README.md
- pom.xml
Resolves
https://issues.redhat.com/browse/MODCLUSTER-740
> MODCLUSTER-740 Switch build to require JDK11 and compile into 1.8 target

- .github/workflows/ci.yml
Resolves
https://issues.redhat.com/browse/MODCLUSTER-745
> MODCLUSTER-745 CI: Optionally test building with JDK 17 as well

- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/ConfigurableProxyConnectorProvider.java
- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/ModClusterListener.java
- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnectorConfiguration.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/ConfigurableProxyConnectorProvider.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/ModClusterListener.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnectorConfiguration.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/ConfigurableProxyConnectorProvider.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/ModClusterListener.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnectorConfiguration.java
Resolves
https://issues.redhat.com/browse/MODCLUSTER-318
> MODCLUSTER-318 Allow mod_cluster connector address to be configurable

- .github/workflows/ci.yml
- container/tomcat/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- container/tomcat85/src/test/java/org/jboss/modcluster/container/tomcat85/TomcatEventHandlerAdapterTestCase.java
- core/src/test/java/org/jboss/modcluster/mcmp/ResetRequestSourceTestCase.java
- pom.xml
Resolves
https://issues.redhat.com/browse/MODCLUSTER-747
https://issues.redhat.com/browse/MODCLUSTER-705
> [1.4] MODCLUSTER-747 CI: Test 1.4.x branch with JDK 11 & 17

- README.md
- code-coverage/pom.xml
- pom.xml
Jira
https://issues.redhat.com/browse/MODCLUSTER-751
> MODCLUSTER-751 Add code coverage reporting to Maven build

- native/include/node.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-750
Upstream commit https://github.com/modcluster/mod_proxy_cluster/commit/c3f8b81f4b88766ff9eaaeaa88b287f8dae225fd
doc: https://github.com/modcluster/docs.modcluster.io/blob/main/docs/src/main/asciidoc/native.adoc#responsefieldsize
> Fix for https://issues.redhat.com/browse/MODCLUSTER-750

- native/mod_manager/mod_manager.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-755
upstream PR: https://github.com/modcluster/mod_proxy_cluster/pull/40
> Fix for MODCLUSTER-755.

- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-756
Upstream PR: https://github.com/modcluster/mod_proxy_cluster/pull/46
> Fix for https://issues.redhat.com/browse/MODCLUSTER-756

- native/mod_manager/mod_manager.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-760
> Fix for https://issues.redhat.com/browse/MODCLUSTER-760

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-770
Fix warning/error when using CFLAGS = -std=c89 -pedantic 
Upstream commit: https://github.com/modcluster/mod_proxy_cluster/commit/85757eb3bea694a21734380622c6219a51ab95c8
> Fix for https://issues.redhat.com/browse/MODCLUSTER-770

- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-761
> Back port of PR42 to 1.3.x

- native/mod_proxy_cluster/mod_proxy_cluster.c
back port of https://github.com/modcluster/mod_proxy_cluster/pull/53
https://issues.redhat.com/browse/MODCLUSTER-640
> Fix for MODCLUSTER-640

- native/mod_cluster_slotmem/sharedmem_util.c
- native/mod_cluster_slotmem/sharedmem_util.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
It just fix warnings/errors that are already fixed in mod_proxy_cluster.
> Fix warnings/errors.

- container/spi/src/main/java/org/jboss/modcluster/container/ContainerEventHandler.java
- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat-10.0/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- container/tomcat-10.1/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat-10.1/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat-8.5/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat-9.0/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- core/src/main/java/org/jboss/modcluster/ModClusterService.java
- core/src/main/java/org/jboss/modcluster/load/metric/impl/DeterministicLoadStateImpl.java
Resolves
https://issues.redhat.com/browse/MODCLUSTER-790
> MODCLUSTER-790 mod_cluster listener throws NPE when deploying a context in Tomcat - refine ContainerEventHandler#add contract and implementation

- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/TomcatContext.java
Fix for https://issues.redhat.com/browse/MODCLUSTER-790
Upstream corresponding PR: https://github.com/modcluster/mod_cluster/pull/713
> Fix for MODCLUSTER-790.

- native/mod_cluster_slotmem/sharedmem_util.c
Fix for https://issues.redhat.com/browse/JBCS-1369
Fix for https://issues.redhat.com/browse/MODCLUSTER-815
The upstream mod_proxy_cluster is NOT affected because it uses ap_mutex_register()/ap_global_mutex_create()  and the corresponding apr_global_mutex*() calls.
> [1.3.x] Fix for JBCS-1369/MODCLUSTER-815

- native/mod_manager/mod_manager.c
Backport from [2.0](https://github.com/modcluster/mod_proxy_cluster/pull/198)
> [1.3] Improve mod_manager's html output

- native/mod_manager/mod_manager.c
Backport of https://github.com/modcluster/mod_proxy_cluster/pull/239
> MODCLUSTER-823: Fix ignored aliases

- .github/workflows/ci.yml
- native/advertise/mod_advertise.c
Fix building with httpd trunk and add it into CI.
https://issues.redhat.com/browse/MODCLUSTER-829
> [1.3.x] Resolve MODCLUSTER-829 and add CI for it

- native/mod_manager/mod_manager.c
ref https://github.com/modcluster/mod_proxy_cluster/pull/291
> MODCLUSTER-551: Fix wrong argument to logging

- bom/pom.xml
- code-coverage/pom.xml
- core/pom.xml
- dist/pom.xml
- load-spi/pom.xml
- pom.xml
Resolves
https://issues.redhat.com/browse/MODCLUSTER-821
> MODCLUSTER-821 Create a BOM file

- .mvn/wrapper/maven-wrapper.properties
- bom/pom.xml
- code-coverage/pom.xml
- pom.xml
Blocked by 
https://github.com/modcluster/mod_cluster/pull/914
Resolves
https://issues.redhat.com/browse/MODCLUSTER-859
https://issues.redhat.com/browse/MODCLUSTER-850
> MODCLUSTER-859 Upgrade jboss-parent to 50 and upgrade to new Nexus release process

- .github/workflows/ci.yml
https://issues.redhat.com/browse/MODCLUSTER-861
> MODCLUSTER-861 CI: apidocs are not archived
