modcluster/mod_cluster

- core/src/main/java/org/jboss/modcluster/advertise/AdvertiseListenerFactory.java
- core/src/main/java/org/jboss/modcluster/advertise/impl/MulticastSocketFactoryImpl.java
- core/src/test/java/org/jboss/modcluster/advertise/AdvertiseListenerImplTestCase.java
- core/src/test/java/org/jboss/modcluster/advertise/MulticastSocketFactoryImplTestCase.java
Trying multiple things to get this working, none helped. I feel like I am reinveting the wheel -- let's do what JGroups is doing. Looking through numerous Jiras on this, since cca. 2008 Bela has been saying that this doesn't work on OS X so I am sceptical if this has ever really worked...
Also includes:
Mirror JGroups behavior
Reenable tests
Include support for Solaris
Rename  the variable to represent better what the property is (was called linuxlike)
Fix redundant and incorrect javadoc
Jira
https://issues.jboss.org/browse/MODCLUSTER-432
> MODCLUSTER-432 Multicast discovery does not work on Mac OS X, fails with "Can't assign requested address"

- native/mod_proxy_cluster/mod_proxy_cluster.c
Addresses the following:
https://issues.jboss.org/browse/MODCLUSTER-461
https://issues.jboss.org/browse/MODCLUSTER-462
https://issues.jboss.org/browse/MODCLUSTER-285
> MODCLUSTER-461 If Session ID key stored in URL contains sticky session cookie name it it used for routing

- native/mod_manager/mod_manager.c
Unlike tomcat, that makes all aliases lower case even if you configure them upper case, undertow sends aliases verbatim - i.e. even upper case or camel case.
Our logic relies on comparing them, so this PR converts aliases to lower case on arrival.
From mod_cluster manager console:
```
</pre><h3>Aliases:</h3><pre>default-host
LOCALHOST
KARM.YADA.YADA.REDHAT.COM
</pre></body></html>
```
```
</pre><h3>Aliases:</h3><pre>default-host
localhost
karm.yada.yada.redhat.com
</pre></body></html>
```
> MODCLUSTER-463 converts aliases for a context on -APP message arrival.

- .travis.yml
The situation has changed since original proposal fixing CI with proper dependencies for tomcat versions. Taking into account support for legacy containers has been dropped in master, so now we have desired combinations:
jdk7 + jdk8 and default profile (excludes Tomcat 9) -> 3 combos on travis
jdk 8 + Tomcat 9 profile -> 1 combo on travis
See http://tomcat.apache.org/whichversion.html
Jira
https://issues.jboss.org/browse/MODCLUSTER-485
> MODCLUSTER-485 Move CI to Travis

- native/mod_manager/domain.c
Additional porting from 1.2.x
Follows up on [pull 191](https://github.com/modcluster/mod_cluster/pull/191)
to match 1.2.x [pull 190](https://github.com/modcluster/mod_cluster/pull/190).
> [1.3] Vol. II Command processing optimizations in domain.c

- native/mod_manager/mod_manager.c
We need mod_cluster and its underlying mod_proxy code to work well with various crazy Balancer names. Back in the day, upper case characters in Balancer name were fixed for ```ManagerBalancerName``` static configuration, see:
* [~~MODCLUSTER-435~~](https://issues.jboss.org/browse/MODCLUSTER-435)
* [~~BZ 1044879~~](https://bugzilla.redhat.com/show_bug.cgi?id=1044879#c0)
A new issue has surfaced, [MODCLUSTER-534](https://issues.jboss.org/browse/MODCLUSTER-534), that concerns Balancer names coming in CONFIG messages from workers. This fix expands [~~MODCLUSTER-435~~](https://issues.jboss.org/browse/MODCLUSTER-435) to cover  [MODCLUSTER-534](https://issues.jboss.org/browse/MODCLUSTER-534).
> MODCLUSTER-534 update to MODCLUSTER-435 normalizing balancer name

- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/ModClusterListener.java
- core/src/main/java/org/jboss/modcluster/ModClusterServiceMBean.java
- core/src/main/java/org/jboss/modcluster/config/impl/ModClusterConfig.java
- core/src/main/java/org/jboss/modcluster/config/impl/SessionDrainingStrategyEnum.java
Does the following:
* MODCLUSTER-498 Extract Tomcat modeler specific methods from ModClusterConfig into separate Tomcat-specific class
* MODCLUSTER-497 ModClusterConfig#setAdvertiseInterface(java.lang.String) should not have been deprecated as it's used by Tomcat modeller
by moving the classes from core into base container implementation for Tomcat.
Jiras
https://issues.jboss.org/browse/MODCLUSTER-498
https://issues.jboss.org/browse/MODCLUSTER-497
Just to note, wildfly master still relies on the following "deprecated" 2 methods that are being moved (so dropping in widlfly wont work, but shouldn't be a problem).
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] …
```
> MODCLUSTER-497 MODCLUSTER-498 Tomcat modeler fixes and code cleanup:

- pom.xml
Needed for JDK9 support also in 1.3.x branch.
Jira
https://issues.jboss.org/browse/MODCLUSTER-539
> MODCLUSTER-539 Support JDK9 build 9-ea+139

- container/tomcat/src/test/java/org/jboss/modcluster/container/catalina/AutoProxyConnectorProviderTestCase.java
- container/tomcat/src/test/java/org/jboss/modcluster/container/catalina/ContainerEventHandlerAdapterTestCase.java
- container/tomcat/src/test/java/org/jboss/modcluster/container/catalina/ContextTestCase.java
- container/tomcat/src/test/java/org/jboss/modcluster/container/catalina/JMXServerProviderTestCase.java
- container/tomcat/src/test/java/org/jboss/modcluster/container/catalina/ServerTestCase.java
- container/tomcat/src/test/java/org/jboss/modcluster/container/catalina/SimpleProxyConnectorProviderTestCase.java
- container/tomcat85/src/test/java/org/jboss/modcluster/container/tomcat85/ServerTestCase.java
- container/tomcat85/src/test/java/org/jboss/modcluster/container/tomcat85/TomcatEventHandlerAdapterTestCase.java
- core/src/test/java/org/jboss/modcluster/load/metric/MBeanAttributeLoadMetricTestCase.java
- core/src/test/java/org/jboss/modcluster/load/metric/MBeanAttributeRatioLoadMetricTestCase.java
- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-560
Needed for JDK9 support.
> MODCLUSTER-560 Upgrade mockito to 2.5.2

- core/src/main/java/org/jboss/modcluster/ModClusterService.java
- core/src/main/java/org/jboss/modcluster/config/AdvertiseConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/BalancerConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/MCMPHandlerConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/ModClusterConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/ProxyConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/SSLConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/builder/AbstractConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/AdvertiseConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/BalancerConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/ConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/Creator.java
- core/src/main/java/org/jboss/modcluster/config/builder/MCMPHandlerConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/ModClusterConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/NodeConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/package-info.java
- core/src/main/java/org/jboss/modcluster/config/impl/AdvertiseConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/BalancerConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/MCMPHandlerConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/ModClusterConfig.java
- core/src/main/java/org/jboss/modcluster/config/impl/ModClusterConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/NodeConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/SystemPropertyJvmRouteFactory.java
- core/src/main/java/org/jboss/modcluster/config/impl/UUIDJvmRouteFactory.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPHandler.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/JSSESocketFactory.java
- core/src/test/java/org/jboss/modcluster/config/builder/ModClusterConfigurationBuilderTest.java
master: https://github.com/modcluster/mod_cluster/pull/238
This branch cannot use diamonds (MCMPHandlerImpl) plus different imports for the config class since there is still more legacy code.
> [1.3] MODCLUSTER-564 Introduce configuration builder API + MODCLUSTER-562 SSL integration 

- core/src/main/java/org/jboss/modcluster/ModClusterService.java
- core/src/main/java/org/jboss/modcluster/config/AdvertiseConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/BalancerConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/MCMPHandlerConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/ModClusterConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/ProxyConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/SSLConfiguration.java
- core/src/main/java/org/jboss/modcluster/config/builder/AbstractConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/AdvertiseConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/BalancerConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/ConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/Creator.java
- core/src/main/java/org/jboss/modcluster/config/builder/MCMPHandlerConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/ModClusterConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/NodeConfigurationBuilder.java
- core/src/main/java/org/jboss/modcluster/config/builder/package-info.java
- core/src/main/java/org/jboss/modcluster/config/impl/AdvertiseConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/BalancerConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/MCMPHandlerConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/ModClusterConfig.java
- core/src/main/java/org/jboss/modcluster/config/impl/ModClusterConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/NodeConfigurationImpl.java
- core/src/main/java/org/jboss/modcluster/config/impl/SystemPropertyJvmRouteFactory.java
- core/src/main/java/org/jboss/modcluster/config/impl/UUIDJvmRouteFactory.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPHandler.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/JSSESocketFactory.java
- core/src/test/java/org/jboss/modcluster/config/builder/ModClusterConfigurationBuilderTest.java
Jiras
https://issues.jboss.org/browse/MODCLUSTER-564
https://issues.jboss.org/browse/MODCLUSTER-562
Currently attempts to maintain 100% backward binary compatibility (for 1.3.x branch) and uses the same previously established configuration concepts.
> MODCLUSTER-564 Introduce configuration builder API + MODCLUSTER-562 SSL integration

- core/src/main/java/org/jboss/modcluster/ModClusterService.java
- core/src/main/java/org/jboss/modcluster/mcmp/ContextFilter.java
- core/src/main/java/org/jboss/modcluster/mcmp/impl/ResetRequestSourceImpl.java
- core/src/test/java/org/jboss/modcluster/mcmp/ResetRequestSourceTestCase.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-566
Upstream
https://github.com/modcluster/mod_cluster/pull/241
> [1.3] MODCLUSTER-566 Exclusion list cannot be pre-populated in init()

- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPRequestFactory.java
https://issues.jboss.org/browse/MODCLUSTER-572
https://github.com/modcluster/mod_cluster/pull/245
> MODCLUSTER-572 Normalize hostnames in MCMP messages

- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-561
https://issues.jboss.org/browse/MODCLUSTER-586
Now mod_cluster builds on JDK9 including the demo!
> MODCLUSTER-561 Upgrade maven-war-plugin to version compatible with JDK 9

- core/src/main/java/org/jboss/modcluster/ModClusterService.java
https://issues.jboss.org/browse/MODCLUSTER-596
> MODCLUSTER-596 mod_cluster stop/stop-context operations do not send STOP-* in when session draining was unsuccessful

- container/tomcat/pom.xml
- container/tomcat/src/main/java/org/jboss/modcluster/container/tomcat/ModClusterListener.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-585 - the tomcat part
> MODCLUSTER-585 mod_cluster excluded-contexts doesn't exclude slash prefixed /contexts; should perform normalization

- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPHandler.java
Enclose IPv6 address into square brackets while sending STATUS info to balancer.
MODCLUSTER-584: https://issues.jboss.org/browse/MODCLUSTER-584
@rhusar - seems that modcluster is trying to resolve IP address to hostname (seems it's another suspect for the automagic plague)
> [MODCLUSTER-584] Enclose IPv6 address into square brackets

- container/tomcat8/src/main/java/org/jboss/modcluster/container/tomcat8/TomcatContext.java
- container/tomcat8/src/main/java/org/jboss/modcluster/container/tomcat8/TomcatEngine.java
- container/tomcat8/src/main/java/org/jboss/modcluster/container/tomcat8/TomcatEngineFactory.java
- container/tomcat8/src/main/resources/META-INF/services/org.jboss.modcluster.container.tomcat.EngineFactory
- container/tomcat8/src/test/java/org/jboss/modcluster/container/tomcat8/EngineTestCase.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-469
Upstream
https://github.com/modcluster/mod_cluster/pull/303
> [1.4] MODCLUSTER-469 Tomcat 8 container integration does not add jvm-route to JSESSIONID when generated by UUIDJvmRouteFactory

- core/src/main/java/org/jboss/modcluster/mcmp/impl/DefaultMCMPHandler.java
Jira
https://issues.jboss.org/browse/MODCLUSTER-639
Here are some steps to simulate a bad proxy:
1. Configure mod_cluster to use good and bad proxy
```
/socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=proxy1:add(host=127.0.0.1,port=9090
/socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=proxy2:add(host=127.0.0.1,port=9190
/subsystem=modcluster/mod-cluster-config=configuration/:write-attribute(name=proxies, value=[proxy1, proxy2]
```
2. Start a fake bad proxy with a python script
```
import socket
import sys
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
s.bind(('localhost', 9190))
except socket.error as e:
sys.exit()
s.listen(5)
while 1:
conn, addr = s.accept()
print 'Connection ' + addr[0] + ':' + str(addr[1]) …
```
> [1.3] MODCLUSTER-639 proxy reset requests can allow for other MCMPs to bad proxy

- .travis.yml
- install-jdk.sh
- pom.xml
Jira
https://issues.jboss.org/browse/MODCLUSTER-649
https://issues.jboss.org/browse/MODCLUSTER-647 Upgrade jboss-logging-processor to 2.1.0.Final
https://issues.jboss.org/browse/MODCLUSTER-648 Upgrade jboss-logging to 3.3.2.Final
https://issues.jboss.org/browse/MODCLUSTER-651 Upgrade jboss-parent to 26
https://issues.jboss.org/browse/MODCLUSTER-650 Travis CI: Expand build matrix to JDK10 and JDK11
> MODCLUSTER-649 Support JDK11 build build 11-ea+3

- docs/src/main/asciidoc/introduction.adoc
HP-UX is no longer being built.
> Removed HP-UX from the list of platforms.

- .gitignore
- dist/src/assembly/demo.xml
- dist/src/assembly/tomcat-component.xml
- dist/src/assembly/tomcat8.xml
- dist/src/assembly/tomcat85.xml
- dist/src/assembly/tomcat9.xml
- install-jdk.sh
Jira
https://issues.jboss.org/browse/MODCLUSTER-656
> MODCLUSTER-656 Remove *-javadoc.jar from distribution profiles

- .gitignore
- dist/src/assembly/demo.xml
- dist/src/assembly/tomcat-component.xml
- dist/src/assembly/tomcat8.xml
- dist/src/assembly/tomcat85.xml
- dist/src/assembly/tomcat9.xml
master
https://github.com/modcluster/mod_cluster/pull/331
Jira
https://issues.jboss.org/browse/MODCLUSTER-656
> [1.4] MODCLUSTER-656 Remove *-javadoc.jar from distribution profiles

- pom.xml
https://issues.jboss.org/browse/MODCLUSTER-691
https://issues.jboss.org/browse/MODCLUSTER-692
> [1.4] MODCLUSTER-691 Upgrade jboss-logging to 3.4.0.Final + MODCLUSTER-692 Upgrade jboss-logging-processor to 2.2.0.Final 

- core/src/main/java/org/jboss/modcluster/ModClusterService.java
- core/src/test/java/org/jboss/modcluster/ModClusterServiceTest.java
This PR is related to issue [MODCLUSTER-700](https://issues.jboss.org/projects/MODCLUSTER/issues/MODCLUSTER-700?filter=allopenissues) and adds a feature of not disabling existing context with a specific path in case of parallel deployment.
> 1.4.x Keeping context in case of Tomcat's parallel deployment [MODCLUSTER-700]

- container/tomcat/src/test/java/org/jboss/modcluster/container/tomcat/ConnectorTestCase.java
- container/tomcat100/src/test/java/org/jboss/modcluster/container/tomcat100/ConnectorTestCase.java
- container/tomcat8/src/test/java/org/jboss/modcluster/container/tomcat8/ConnectorTestCase.java
- pom.xml
* update tests because since 7.0.100, 8.5.51, 9.0.31, and 10.0.0-M3 the default bind address for the AJP/1.3 connector is the loopback address
> Upgrade Tomcat to 7.0.103, 8.5.53, and 9.0.33

- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/SingleServiceServer.java
- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat-10.0/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/SingleServiceServer.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat-8.5/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/SingleServiceServer.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatEventHandlerAdapter.java
- container/tomcat-9.0/src/test/java/org/jboss/modcluster/container/tomcat/ContainerEventHandlerAdapterTestCase.java
Resolves
https://issues.redhat.com/browse/MODCLUSTER-720
Already partially reviewed here - https://github.com/modcluster/mod_cluster/pull/455
> MODCLUSTER-720 Allow mod_cluster listener to register at <Service> level rather than <Server> level

- .github/workflows/ci.yml
- core/src/main/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerImpl.java
- core/src/test/java/org/jboss/modcluster/advertise/impl/AdvertiseListenerImplTestCase.java
- core/src/test/java/org/jboss/modcluster/advertise/impl/DatagramChannelFactoryImplTestCase.java
Resolves
https://issues.redhat.com/browse/MODCLUSTER-742
https://issues.redhat.com/browse/MODCLUSTER-743
> MODCLUSTER-743 Building using JDK 11 but running on JDK 8 yields java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer; + CI

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-758
> [MODCLUSTER-758] improve proxy_cluster_post_request locking

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-757
> [MODCLUSTER-757] improve internal_find_best_byrequests performance for high balancer members

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-765
upstream PR https://github.com/modcluster/mod_proxy_cluster/pull/49
> Fix for MODCLUSTER-765.

- native/mod_proxy_cluster/mod_proxy_cluster.c
Follow up to fix regressions in https://issues.redhat.com/browse/MODCLUSTER-765
> Arrange the cache logic for vhost and context.

- .github/workflows/ci.yml
- pom.xml
Resolves
https://issues.redhat.com/browse/MODCLUSTER-772
> MODCLUSTER-772 Require JDK 11 as a minimum for the runtime

- native/mod_proxy_cluster/mod_proxy_cluster.c
Something like:
<Proxy balancer://testAP>
BalancerMember http://localhost:8080/
BalancerMember http://localhost:8081/
is not supported but no error/warning were used, the fix adds a error message and refuses to start httpd.
> Fix for https://issues.redhat.com/browse/MODCLUSTER-771

- native/mod_proxy_cluster/mod_proxy_cluster.c
Improve debugging when using ProxyPass
return 404 instead 503 when no context corresponding to the ProxyPass.
follow up of https://issues.redhat.com/browse/MODCLUSTER-640
upstream PR: https://github.com/modcluster/mod_proxy_cluster/pull/79
> Improve debugging when using ProxyPass

- native/mod_proxy_cluster/mod_proxy_cluster.c
No need to fix 2.0.x / main the logic there uses only 1 worker.
> Fix for https://issues.redhat.com/browse/MODCLUSTER-785

- pom.xml
https://issues.redhat.com/browse/MODCLUSTER-789
> MODCLUSTER-789 Remove wrongly placed <goals> tag to enable Maven 4.x

- container/tomcat-10.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatContext.java
- container/tomcat-10.1/src/main/java/org/jboss/modcluster/container/tomcat/TomcatContext.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/TomcatContext.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatContext.java
While doing test deploying and undeploying webapps by adding and removing war files I noted the exception, so here is the PR. Same occurs on 1.4.x
> Prevent exception.

- native/mod_proxy_cluster/mod_proxy_cluster.c
Now compilation fails for httpd 2.4.48 and older. https://issues.redhat.com/browse/MODCLUSTER-802
> [1.3.x] MODCLUSTER-802: Fail compilation on unsupported httpd versions (< 2.4.49)

- container/spi/src/main/java/org/jboss/modcluster/container/Connector.java
- container/tomcat-10.1/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/SingleServiceServer.java
- container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
- container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/TomcatConnector.java
Resolves
https://issues.redhat.com/browse/MODCLUSTER-798
Replaces https://github.com/modcluster/mod_cluster/pull/735
> MODCLUSTER-798 Add support for server portOffset configuration in Tomcat

- .github/workflows/ci.yml
- pom.xml
Resolves
https://issues.redhat.com/browse/MODCLUSTER-812
and adds JDK 22-ea support.
Replaces https://github.com/modcluster/mod_cluster/pull/757
> MODCLUSTER-812 Configure jboss-logging annotation processing via maven-compiler-plugin's annotationProcessorPaths + add JDK 22-ea support

- native/mod_manager/mod_manager.c
backport of https://github.com/modcluster/mod_proxy_cluster/pull/202
> [1.3.x] MODCLUSTER-551 Fix spelling of EnableMCPMReceive option.

- .github/workflows/ci.yml
- pom.xml
Resolves
https://issues.redhat.com/browse/MODCLUSTER-837
https://issues.redhat.com/browse/MODCLUSTER-836
> MODCLUSTER-837 CI: Add Javadoc aggregate build to the testing pipeline + MODCLUSTER-836 Building the aggregate Javadoc site fails the build

- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix: https://issues.redhat.com/browse/MODCLUSTER-841
This change is NOT relevant in upstream, the  http/ws logic is different.
> Fix for MODCLUSTER-841, use updated to propagate the status and error_time.

- native/mod_proxy_cluster/mod_proxy_cluster.c
Backport
https://github.com/modcluster/mod_proxy_cluster/pull/267
https://github.com/modcluster/mod_proxy_cluster/pull/269
> Clear worker status when reused, fix find_node_context_host condition

- docs/userguide/src/main/docbook/modules/faq.xml
- docs/userguide/src/main/docbook/modules/quick-start.xml
- native/mod_manager/mod_manager.c
- test/java/README.txt
- test/java/installhttpd.sh
backport for https://github.com/modcluster/mod_proxy_cluster/pull/309
> [1.3.x] Change the example directive to be consistent with the docs

- .github/workflows/ci.yml
- container/tomcat-11.0/pom.xml
- pom.xml
* Cleans up a lot of build cruft needed to support both 11/17 
* and significantly reduces required CI. 
* Uses maven-wrapper for deterministic builds.
Resolves
https://issues.redhat.com/browse/MODCLUSTER-848
> MODCLUSTER-848 Move to Java SE 17 as the minimum SE version

- core/src/main/java/org/jboss/modcluster/ModClusterLogger.java
- core/src/main/java/org/jboss/modcluster/advertise/impl/DatagramChannelFactoryImpl.java
- core/src/test/java/org/jboss/modcluster/advertise/impl/DatagramChannelFactoryImplTestCase.java
Resolves
https://issues.redhat.com/browse/MODCLUSTER-779
Removes links to non-editable and honestly no longer relevant pages.
> MODCLUSTER-779 Remove or fix broken links in logs pointing to jboss.org

- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-852.
Changes in httpd-2.4.59 are causing the sockets to stop being reused, that results in many sockets in TIME_WAIT and on windows when doing a load tests to get "All workers are in error state" due to:
(OS 10048) Only one usage of each socket address (protocol/network address/port) is normally permitted.
because the OS runs out of sockets.
Note that increasing the number of socket in the OS helps to some extend:
netsh int ipv4 set dynamicport tcp start=9000 num=25000
netsh int ipv6 set dynamicport tcp start=9000 num=25000
Note the same fix is need in mod_proxy_cluster upstream.
> Fix for https://issues.redhat.com/browse/MODCLUSTER-852.

- pom.xml
https://issues.redhat.com/browse/MODCLUSTER-854
I just assumed that jboss-parent does this, but it does not currently set it the way we have set it up.
> MODCLUSTER-854 Fix compilation warnings with newer JDKs

- .github/ISSUE_TEMPLATE/ci.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/java-mod_cluster.md
- .github/ISSUE_TEMPLATE/native-mod_proxy_cluster.md
I added only a few templates as it does not make sense to create templates for all possible combinations. It might be nice to have this for some basic triaging (until we move 1.3.x to the next repository, but maybe even then we could just update the template with a redirect info).
> Add a few basic GitHub issue templates

- .github/workflows/ci.yml
Resolves https://github.com/modcluster/mod_cluster/issues/895
> ci: add JDK 25-ea (the next LTS release) to the testing matrix (#895)
